#开发环境的配置
#server.port=8443
server:
  port: 9090
#  context-path: /ziniu
# SSL协议相关配置
#server.ssl.key-store= .keystore
#server.ssl.key-password= 123321
#server.ssl.key-store-type= JKS
#server.ssl.key-alias= tomcat

spring:
    application:
        name: dev
    #数据源配置
    datasource:
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://rds0473qn129qi882964.mysql.rds.aliyuncs.com:3306/znxz?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
        username: qiuxm
        password: ENC(GPD81o7A2J5Ic3KCDrN3/ZJ8cnrh8dcE)
        type: com.alibaba.druid.pool.DruidDataSourceC3P0Adapter
        #初始化大小，最小，最大
        maxActive: 20
        initialSize: 5
        minIdle: 5
        #配置获取连接等待超时时间，单位毫秒
        maxWait: 60000
        #需要关闭空闲连接的检测时间，单位毫秒
        timeBetweenEvictionRunsMillis: 60000
        #连接在池中最小生存时间，单位毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        #打开PScache,并指定每个连接上PScache大小
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
        #配置监控统计拦截的filters,去掉后监控界面的sql将无法统计，wall用于防火墙
        filters: stat,wall,log4j
        tomcat:
          connection-properties: druid.stat.mergeSql=true;druid.stat.showSqlMills=5000


    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
    jackson:
      serialization: true
    thymeleaf:
      cache: false
    activemq:
      broker-url: failover:tcp://192.168.10.55:61616
      in-memory: false


#prefix 默认是在classpath:/templates/下
#      prefix: classpath:/static/

#jms相关配置
activemq:
    broker-url: spring.activemq.broker-url=tcp://192.168.10.55:61616

#mybatis配置
mybatis:
    mapperLocations: classpath:com.ziuniu.mapper/*.xml

#业务参数属性配置
book:
  author: 菡萏如佳人
  name: it and poem

author:
  name: 临江仙
  age:  32

ziniu:
  yinyoushiren: 临江仙
  defaultjms: default_queue
  goldjms: gold_queue

#日志配置
logging:
  file: D:/springboot.log
  level:
     com.ziniu.web : debug
     com.ziniu.controller : debug


jasypt:
  encryptor:
    password: ziniu


